version: '3.9'
services:
  node:
    build: .
    command: start:dev
    volumes:
      - .:/app
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV:development
      - PORT=3001
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=usuario
      - DATABASE_PASSWORD=senha
      - DATABASE_NAME=url_shortener
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
